# Generated by Django 3.2.9 on 2021-11-21 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BRoute',
            fields=[
                ('r_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='No title', max_length=200)),
                ('route', models.TextField()),
                ('distance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('INTERMEDIATE', 'Intermediate'), ('DIFFICULT', 'Difficult')], default='EASY', max_length=15)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('edited', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('userFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'broutes',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('c_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('routeFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broutes.broute')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
