# Generated by Django 3.2.9 on 2021-11-22 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broutes', '0002_auto_20211121_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='routeFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='broutes.broute'),
        ),
    ]
