# Generated by Django 3.2.9 on 2021-11-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broutes', '0004_auto_20211122_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broute',
            name='bbox',
        ),
        migrations.AlterField(
            model_name='broute',
            name='distance',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
    ]
